name: SYNC
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
  - cron:  '15 * * * *'
  
jobs:
   sync:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync user/repo -b main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
